REPO_ROOT=$(dirname $(readlink -f $0))/../..

# Export desktop environment shell configuration
eval "$($REPO_ROOT/docker/scripts/environment.sh)"

# Get host user password to apply to container user
export DESKTOP_ENVIRONMENT_HOST_USER_PASSWORD=$(sudo cat /etc/shadow | grep $DESKTOP_ENVIRONMENT_USER | cut -d: -f2)

# Capture build start time
BUILD_START_TIME=$(date +%s)

docker build \
  --build-arg CACHEBUST_APPS=$(cat $REPO_ROOT/.cachebust-apps 2>/dev/null) \
  --build-arg CACHEBUST_DOTFILES=$(cat $REPO_ROOT/.cachebust-dotfiles 2>/dev/null) \
  --build-arg DESKTOP_ENVIRONMENT_CONTAINER_GIT_SHA=$(git --git-dir $REPO_ROOT/.git rev-parse HEAD | cut -b 1-7) \
  --build-arg DESKTOP_ENVIRONMENT_CONTAINER_BUILD_DATE=$(date +%s) \
  --build-arg DESKTOP_ENVIRONMENT_CONTAINER_IMAGE_NAME=$DESKTOP_ENVIRONMENT_REGISTRY/$DESKTOP_ENVIRONMENT_CONTAINER_IMAGE \
  --build-arg DESKTOP_ENVIRONMENT_GITHUB_USER=$DESKTOP_ENVIRONMENT_GITHUB_USER \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_HOME=$DESKTOP_ENVIRONMENT_SOURCE_HOME \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_ALACRITTY=$DESKTOP_ENVIRONMENT_SOURCE_ALACRITTY \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_BPLAY=$DESKTOP_ENVIRONMENT_SOURCE_BPLAY \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_CBONSAI=$DESKTOP_ENVIRONMENT_SOURCE_CBONSAI \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_DESKTOP_ENVIRONMENT=$DESKTOP_ENVIRONMENT_SOURCE_DESKTOP_ENVIRONMENT \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_DNCLI=$DESKTOP_ENVIRONMENT_SOURCE_DNCLI \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_DUNST=$DESKTOP_ENVIRONMENT_SOURCE_DUNST \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_FASTFETCH=$DESKTOP_ENVIRONMENT_SOURCE_FASTFETCH \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_GIT=$DESKTOP_ENVIRONMENT_SOURCE_GIT \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_GOTOP=$DESKTOP_ENVIRONMENT_SOURCE_GOTOP \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_GPING=$DESKTOP_ENVIRONMENT_SOURCE_GPING \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_GSIMPLECAL=$DESKTOP_ENVIRONMENT_SOURCE_GSIMPLECAL \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_I3=$DESKTOP_ENVIRONMENT_SOURCE_I3 \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_I3BLOCKS=$DESKTOP_ENVIRONMENT_SOURCE_I3BLOCKS \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_I3LOCK=$DESKTOP_ENVIRONMENT_SOURCE_I3LOCK \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_JOBBER=$DESKTOP_ENVIRONMENT_SOURCE_JOBBER \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_JUMP=$DESKTOP_ENVIRONMENT_SOURCE_JUMP \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_NCMPCPP=$DESKTOP_ENVIRONMENT_SOURCE_NCMPCPP \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_NICOTINE_PLUS=$DESKTOP_ENVIRONMENT_SOURCE_NICOTINE_PLUS \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_NOVNC=$DESKTOP_ENVIRONMENT_SOURCE_NOVNC \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_PCMANFM=$DESKTOP_ENVIRONMENT_SOURCE_PCMANFM \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_PICOM=$DESKTOP_ENVIRONMENT_SOURCE_PICOM \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_PYWAL=$DESKTOP_ENVIRONMENT_SOURCE_PYWAL \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_QJACKCTL=$DESKTOP_ENVIRONMENT_SOURCE_QJACKCTL \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_QPWGRAPH=$DESKTOP_ENVIRONMENT_SOURCE_QPWGRAPH \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_QT5CT=$DESKTOP_ENVIRONMENT_SOURCE_QT5CT \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_SCREENPIPE=$DESKTOP_ENVIRONMENT_SOURCE_SCREENPIPE \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_TMUX=$DESKTOP_ENVIRONMENT_SOURCE_TMUX \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_VCSH=$DESKTOP_ENVIRONMENT_SOURCE_VCSH \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_VSCODE_WAL=$DESKTOP_ENVIRONMENT_SOURCE_VSCODE_WAL \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_WAL_CHROME_EXTENSION=$DESKTOP_ENVIRONMENT_SOURCE_WAL_CHROME_EXTENSION \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_WALOGRAM=$DESKTOP_ENVIRONMENT_SOURCE_WALOGRAM \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_WARNAI=$DESKTOP_ENVIRONMENT_SOURCE_WARNAI \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_WHATFILES=$DESKTOP_ENVIRONMENT_SOURCE_WHATFILES \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_XSETTINGSD=$DESKTOP_ENVIRONMENT_SOURCE_XSETTINGSD \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_XWINWRAP=$DESKTOP_ENVIRONMENT_SOURCE_XWINWRAP \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_ZEROCLAW=$DESKTOP_ENVIRONMENT_SOURCE_ZEROCLAW \
  --build-arg DESKTOP_ENVIRONMENT_SOURCE_ZSH=$DESKTOP_ENVIRONMENT_SOURCE_ZSH \
  --build-arg DESKTOP_ENVIRONMENT_USER=$DESKTOP_ENVIRONMENT_USER \
  --file $REPO_ROOT/docker/Dockerfile \
  --secret id=user_password,env=DESKTOP_ENVIRONMENT_HOST_USER_PASSWORD \
  --tag $DESKTOP_ENVIRONMENT_REGISTRY/$DESKTOP_ENVIRONMENT_CONTAINER_IMAGE:$DESKTOP_ENVIRONMENT_CONTAINER_TAG \
  --tag $DESKTOP_ENVIRONMENT_REGISTRY/$DESKTOP_ENVIRONMENT_CONTAINER_IMAGE:latest \
  $REPO_ROOT/docker \
  $@

# Capture build exit code
BUILD_EXIT_CODE=$?

# Store build exit code
echo $BUILD_EXIT_CODE > $REPO_ROOT/.build-exit-code

# Store build end time
echo $(date +%s) > $REPO_ROOT/.build-exit-time

# Report build time
echo "Build time: $(($(date +%s) - BUILD_START_TIME))s."

# Exit with build exit code
exit $BUILD_EXIT_CODE
