name: Build Desktop Environment From Dotfiles
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write
    steps:

      - name: Record workflow start time
        run: echo "TIME_WORKFLOW_START=$(date +%s)" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sanitise repository owner
        run: echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Record build start
        run: echo "TIME_BUILD_START=$(date +%s)" >> $GITHUB_ENV

      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: |
            CACHEBUST_DOTFILES=${{ github.sha }}
            DESKTOP_ENVIRONMENT_USER=${{ env.REPOSITORY_OWNER }}
            DESKTOP_ENVIRONMENT_GITHUB_USER=${{ env.REPOSITORY_OWNER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/Dockerfile
          load: true
          push: false
          tags: ghcr.io/${{ env.REPOSITORY_OWNER }}/desktop-environment:latest

      - name: Record build end
        if: always()
        run: echo "TIME_BUILD_END=$(date +%s)" >> $GITHUB_ENV

      - name: Record push start
        run: echo "TIME_PUSH_START=$(date +%s)" >> $GITHUB_ENV

      - name: Push to GitHub Container Registry
        id: push
        run: docker push ghcr.io/${{ env.REPOSITORY_OWNER }}/desktop-environment:latest

      - name: Record push end
        if: always()
        run: echo "TIME_PUSH_END=$(date +%s)" >> $GITHUB_ENV

      - name: Run desktop environment tests
        id: test
        run: ./docker/scripts/test.sh
        env:
          DESKTOP_ENVIRONMENT_REGISTRY: ghcr.io/${{ env.REPOSITORY_OWNER }}
        continue-on-error: true

      - name: Generate workflow summary
        if: always()
        env:
          STEP_BUILD_OUTCOME: ${{ steps.build.outcome }}
          STEP_PUSH_OUTCOME: ${{ steps.push.outcome }}
          STEP_TEST_OUTCOME: ${{ steps.test.outcome }}
          JOB_STATUS: ${{ job.status }}
        run: bash .github/scripts/generate-summary.sh
